# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1181, 822)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Left_Frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Left_Frame.sizePolicy().hasHeightForWidth())
        self.Left_Frame.setSizePolicy(sizePolicy)
        self.Left_Frame.setMaximumSize(QtCore.QSize(419, 16777215))
        self.Left_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Left_Frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Left_Frame.setObjectName("Left_Frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Left_Frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.Left_Frame)
        self.tabWidget.setObjectName("tabWidget")
        self.Nodes_Tab = QtWidgets.QWidget()
        self.Nodes_Tab.setObjectName("Nodes_Tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Nodes_Tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.Nodes_Tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Nodes_Table_Widget = QtWidgets.QTableWidget(self.groupBox)
        self.Nodes_Table_Widget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.Nodes_Table_Widget.setAlternatingRowColors(True)
        self.Nodes_Table_Widget.setRowCount(0)
        self.Nodes_Table_Widget.setObjectName("Nodes_Table_Widget")
        self.Nodes_Table_Widget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Nodes_Table_Widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Nodes_Table_Widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Nodes_Table_Widget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.Nodes_Table_Widget)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Nodes_Tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Add_Remove_Grid = QtWidgets.QGridLayout()
        self.Add_Remove_Grid.setContentsMargins(5, -1, 5, -1)
        self.Add_Remove_Grid.setObjectName("Add_Remove_Grid")
        self.Node_Number_LEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.Node_Number_LEdit.setEnabled(False)
        self.Node_Number_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Node_Number_LEdit.setObjectName("Node_Number_LEdit")
        self.Add_Remove_Grid.addWidget(self.Node_Number_LEdit, 1, 0, 1, 1)
        self.X_Coord_Label = QtWidgets.QLabel(self.groupBox_2)
        self.X_Coord_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Coord_Label.setObjectName("X_Coord_Label")
        self.Add_Remove_Grid.addWidget(self.X_Coord_Label, 0, 1, 1, 1)
        self.X_Coord_LEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.X_Coord_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Coord_LEdit.setObjectName("X_Coord_LEdit")
        self.Add_Remove_Grid.addWidget(self.X_Coord_LEdit, 1, 1, 1, 1)
        self.Y_Coord_Label = QtWidgets.QLabel(self.groupBox_2)
        self.Y_Coord_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_Coord_Label.setObjectName("Y_Coord_Label")
        self.Add_Remove_Grid.addWidget(self.Y_Coord_Label, 0, 2, 1, 1)
        self.Node_Number_Label = QtWidgets.QLabel(self.groupBox_2)
        self.Node_Number_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Node_Number_Label.setObjectName("Node_Number_Label")
        self.Add_Remove_Grid.addWidget(self.Node_Number_Label, 0, 0, 1, 1)
        self.Add_Node_Button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Add_Node_Button.sizePolicy().hasHeightForWidth())
        self.Add_Node_Button.setSizePolicy(sizePolicy)
        self.Add_Node_Button.setObjectName("Add_Node_Button")
        self.Add_Remove_Grid.addWidget(self.Add_Node_Button, 2, 0, 1, 1)
        self.Y_Coord_LEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.Y_Coord_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_Coord_LEdit.setObjectName("Y_Coord_LEdit")
        self.Add_Remove_Grid.addWidget(self.Y_Coord_LEdit, 1, 2, 1, 1)
        self.Plot_Nodes_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.Plot_Nodes_Button.setObjectName("Plot_Nodes_Button")
        self.Add_Remove_Grid.addWidget(self.Plot_Nodes_Button, 4, 0, 1, 3)
        self.Remove_Node_Button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Remove_Node_Button.sizePolicy().hasHeightForWidth())
        self.Remove_Node_Button.setSizePolicy(sizePolicy)
        self.Remove_Node_Button.setObjectName("Remove_Node_Button")
        self.Add_Remove_Grid.addWidget(self.Remove_Node_Button, 2, 1, 1, 1)
        self.Renumber_Nodes_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.Renumber_Nodes_Button.setObjectName("Renumber_Nodes_Button")
        self.Add_Remove_Grid.addWidget(self.Renumber_Nodes_Button, 2, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.Add_Remove_Grid)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.setStretch(0, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.Nodes_Tab, "")
        self.Elements_Tab = QtWidgets.QWidget()
        self.Elements_Tab.setObjectName("Elements_Tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Elements_Tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Elements_Tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Element_Table_Widget = QtWidgets.QTableWidget(self.groupBox_3)
        self.Element_Table_Widget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.Element_Table_Widget.setAlternatingRowColors(True)
        self.Element_Table_Widget.setRowCount(0)
        self.Element_Table_Widget.setObjectName("Element_Table_Widget")
        self.Element_Table_Widget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Element_Table_Widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Element_Table_Widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Element_Table_Widget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_4.addWidget(self.Element_Table_Widget)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Elements_Tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Add_Remove_Bars_Grid = QtWidgets.QGridLayout()
        self.Add_Remove_Bars_Grid.setContentsMargins(5, -1, 5, -1)
        self.Add_Remove_Bars_Grid.setObjectName("Add_Remove_Bars_Grid")
        self.Bar_Number_Label = QtWidgets.QLabel(self.groupBox_4)
        self.Bar_Number_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Bar_Number_Label.setObjectName("Bar_Number_Label")
        self.Add_Remove_Bars_Grid.addWidget(self.Bar_Number_Label, 0, 0, 1, 1)
        self.Node_1_LEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.Node_1_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Node_1_LEdit.setObjectName("Node_1_LEdit")
        self.Add_Remove_Bars_Grid.addWidget(self.Node_1_LEdit, 1, 1, 1, 1)
        self.Node_1_Label = QtWidgets.QLabel(self.groupBox_4)
        self.Node_1_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Node_1_Label.setObjectName("Node_1_Label")
        self.Add_Remove_Bars_Grid.addWidget(self.Node_1_Label, 0, 1, 1, 1)
        self.Add_Bar_Button = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Add_Bar_Button.sizePolicy().hasHeightForWidth())
        self.Add_Bar_Button.setSizePolicy(sizePolicy)
        self.Add_Bar_Button.setObjectName("Add_Bar_Button")
        self.Add_Remove_Bars_Grid.addWidget(self.Add_Bar_Button, 2, 0, 1, 1)
        self.Node_2_Label = QtWidgets.QLabel(self.groupBox_4)
        self.Node_2_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Node_2_Label.setObjectName("Node_2_Label")
        self.Add_Remove_Bars_Grid.addWidget(self.Node_2_Label, 0, 2, 1, 1)
        self.Node_2_LEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.Node_2_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Node_2_LEdit.setObjectName("Node_2_LEdit")
        self.Add_Remove_Bars_Grid.addWidget(self.Node_2_LEdit, 1, 2, 1, 1)
        self.Bar_Number_LEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.Bar_Number_LEdit.setEnabled(False)
        self.Bar_Number_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Bar_Number_LEdit.setObjectName("Bar_Number_LEdit")
        self.Add_Remove_Bars_Grid.addWidget(self.Bar_Number_LEdit, 1, 0, 1, 1)
        self.Plot_Nodes_and_Bars_Button = QtWidgets.QPushButton(self.groupBox_4)
        self.Plot_Nodes_and_Bars_Button.setObjectName("Plot_Nodes_and_Bars_Button")
        self.Add_Remove_Bars_Grid.addWidget(self.Plot_Nodes_and_Bars_Button, 4, 0, 1, 3)
        self.Remove_Bar_Button = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Remove_Bar_Button.sizePolicy().hasHeightForWidth())
        self.Remove_Bar_Button.setSizePolicy(sizePolicy)
        self.Remove_Bar_Button.setObjectName("Remove_Bar_Button")
        self.Add_Remove_Bars_Grid.addWidget(self.Remove_Bar_Button, 2, 1, 1, 1)
        self.Renumber_Bar_Button = QtWidgets.QPushButton(self.groupBox_4)
        self.Renumber_Bar_Button.setObjectName("Renumber_Bar_Button")
        self.Add_Remove_Bars_Grid.addWidget(self.Renumber_Bar_Button, 2, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.Add_Remove_Bars_Grid)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.verticalLayout_3.setStretch(0, 2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.Elements_Tab, "")
        self.Material_Tab = QtWidgets.QWidget()
        self.Material_Tab.setObjectName("Material_Tab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Material_Tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Material_Tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Material_Table_Widget = QtWidgets.QTableWidget(self.groupBox_5)
        self.Material_Table_Widget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.Material_Table_Widget.setAlternatingRowColors(True)
        self.Material_Table_Widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Material_Table_Widget.setRowCount(0)
        self.Material_Table_Widget.setObjectName("Material_Table_Widget")
        self.Material_Table_Widget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Material_Table_Widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Material_Table_Widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Material_Table_Widget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_6.addWidget(self.Material_Table_Widget)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.Material_Tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Add_Remove_Material_Grid = QtWidgets.QGridLayout()
        self.Add_Remove_Material_Grid.setContentsMargins(5, -1, 5, -1)
        self.Add_Remove_Material_Grid.setObjectName("Add_Remove_Material_Grid")
        self.Area_Label = QtWidgets.QLabel(self.groupBox_6)
        self.Area_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Area_Label.setObjectName("Area_Label")
        self.Add_Remove_Material_Grid.addWidget(self.Area_Label, 0, 0, 1, 1)
        self.Area_LEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.Area_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Area_LEdit.setObjectName("Area_LEdit")
        self.Add_Remove_Material_Grid.addWidget(self.Area_LEdit, 1, 0, 1, 1)
        self.Elasticity_LEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.Elasticity_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Elasticity_LEdit.setObjectName("Elasticity_LEdit")
        self.Add_Remove_Material_Grid.addWidget(self.Elasticity_LEdit, 1, 1, 1, 1)
        self.Elasticity_Label = QtWidgets.QLabel(self.groupBox_6)
        self.Elasticity_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Elasticity_Label.setObjectName("Elasticity_Label")
        self.Add_Remove_Material_Grid.addWidget(self.Elasticity_Label, 0, 1, 1, 1)
        self.Update_Material_Button = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Update_Material_Button.sizePolicy().hasHeightForWidth())
        self.Update_Material_Button.setSizePolicy(sizePolicy)
        self.Update_Material_Button.setObjectName("Update_Material_Button")
        self.Add_Remove_Material_Grid.addWidget(self.Update_Material_Button, 2, 0, 1, 2)
        self.horizontalLayout_8.addLayout(self.Add_Remove_Material_Grid)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.verticalLayout_5.setStretch(0, 2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.Material_Tab, "")
        self.Forces_Tab = QtWidgets.QWidget()
        self.Forces_Tab.setObjectName("Forces_Tab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Forces_Tab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Forces_Tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Force_Table_Widget = QtWidgets.QTableWidget(self.groupBox_7)
        self.Force_Table_Widget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.Force_Table_Widget.setAlternatingRowColors(True)
        self.Force_Table_Widget.setRowCount(0)
        self.Force_Table_Widget.setObjectName("Force_Table_Widget")
        self.Force_Table_Widget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Force_Table_Widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Force_Table_Widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Force_Table_Widget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_10.addWidget(self.Force_Table_Widget)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.Forces_Tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Add_Remove_Forces_Grid = QtWidgets.QGridLayout()
        self.Add_Remove_Forces_Grid.setContentsMargins(5, -1, 5, -1)
        self.Add_Remove_Forces_Grid.setObjectName("Add_Remove_Forces_Grid")
        self.Force_Y_Label = QtWidgets.QLabel(self.groupBox_8)
        self.Force_Y_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Force_Y_Label.setObjectName("Force_Y_Label")
        self.Add_Remove_Forces_Grid.addWidget(self.Force_Y_Label, 0, 2, 1, 1)
        self.Force_X_LEdit = QtWidgets.QLineEdit(self.groupBox_8)
        self.Force_X_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Force_X_LEdit.setObjectName("Force_X_LEdit")
        self.Add_Remove_Forces_Grid.addWidget(self.Force_X_LEdit, 1, 1, 1, 1)
        self.Force_Node_Number_LEdit = QtWidgets.QLineEdit(self.groupBox_8)
        self.Force_Node_Number_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Force_Node_Number_LEdit.setObjectName("Force_Node_Number_LEdit")
        self.Add_Remove_Forces_Grid.addWidget(self.Force_Node_Number_LEdit, 1, 0, 1, 1)
        self.Force_Y_LEdit = QtWidgets.QLineEdit(self.groupBox_8)
        self.Force_Y_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Force_Y_LEdit.setObjectName("Force_Y_LEdit")
        self.Add_Remove_Forces_Grid.addWidget(self.Force_Y_LEdit, 1, 2, 1, 1)
        self.Force_Node_Number_Label = QtWidgets.QLabel(self.groupBox_8)
        self.Force_Node_Number_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Force_Node_Number_Label.setObjectName("Force_Node_Number_Label")
        self.Add_Remove_Forces_Grid.addWidget(self.Force_Node_Number_Label, 0, 0, 1, 1)
        self.Remove_Force_Button = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Remove_Force_Button.sizePolicy().hasHeightForWidth())
        self.Remove_Force_Button.setSizePolicy(sizePolicy)
        self.Remove_Force_Button.setObjectName("Remove_Force_Button")
        self.Add_Remove_Forces_Grid.addWidget(self.Remove_Force_Button, 2, 2, 1, 1)
        self.Force_X_Label = QtWidgets.QLabel(self.groupBox_8)
        self.Force_X_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Force_X_Label.setObjectName("Force_X_Label")
        self.Add_Remove_Forces_Grid.addWidget(self.Force_X_Label, 0, 1, 1, 1)
        self.Plot_Forces_Button = QtWidgets.QPushButton(self.groupBox_8)
        self.Plot_Forces_Button.setObjectName("Plot_Forces_Button")
        self.Add_Remove_Forces_Grid.addWidget(self.Plot_Forces_Button, 3, 0, 1, 3)
        self.Add_Force_Button = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Add_Force_Button.sizePolicy().hasHeightForWidth())
        self.Add_Force_Button.setSizePolicy(sizePolicy)
        self.Add_Force_Button.setObjectName("Add_Force_Button")
        self.Add_Remove_Forces_Grid.addWidget(self.Add_Force_Button, 2, 0, 1, 2)
        self.horizontalLayout_11.addLayout(self.Add_Remove_Forces_Grid)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        self.verticalLayout_7.setStretch(0, 2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.Forces_Tab, "")
        self.Supports_Tab = QtWidgets.QWidget()
        self.Supports_Tab.setObjectName("Supports_Tab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Supports_Tab)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.Supports_Tab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Support_Table_Widget = QtWidgets.QTableWidget(self.groupBox_9)
        self.Support_Table_Widget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.Support_Table_Widget.setAlternatingRowColors(True)
        self.Support_Table_Widget.setRowCount(0)
        self.Support_Table_Widget.setObjectName("Support_Table_Widget")
        self.Support_Table_Widget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Support_Table_Widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Support_Table_Widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Support_Table_Widget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_9.addWidget(self.Support_Table_Widget)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.Supports_Tab)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Add_Remove_Supports_Grid = QtWidgets.QGridLayout()
        self.Add_Remove_Supports_Grid.setContentsMargins(5, -1, 5, -1)
        self.Add_Remove_Supports_Grid.setObjectName("Add_Remove_Supports_Grid")
        self.Support_Node_Label = QtWidgets.QLabel(self.groupBox_10)
        self.Support_Node_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Support_Node_Label.setObjectName("Support_Node_Label")
        self.Add_Remove_Supports_Grid.addWidget(self.Support_Node_Label, 0, 0, 1, 1)
        self.X_Coord_ComboBox = QtWidgets.QComboBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_Coord_ComboBox.sizePolicy().hasHeightForWidth())
        self.X_Coord_ComboBox.setSizePolicy(sizePolicy)
        self.X_Coord_ComboBox.setObjectName("X_Coord_ComboBox")
        self.X_Coord_ComboBox.addItem("")
        self.X_Coord_ComboBox.addItem("")
        self.Add_Remove_Supports_Grid.addWidget(self.X_Coord_ComboBox, 1, 1, 1, 1)
        self.Y_Coord_Support_Label = QtWidgets.QLabel(self.groupBox_10)
        self.Y_Coord_Support_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_Coord_Support_Label.setObjectName("Y_Coord_Support_Label")
        self.Add_Remove_Supports_Grid.addWidget(self.Y_Coord_Support_Label, 0, 2, 1, 1)
        self.Y_Coord_ComboBox = QtWidgets.QComboBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y_Coord_ComboBox.sizePolicy().hasHeightForWidth())
        self.Y_Coord_ComboBox.setSizePolicy(sizePolicy)
        self.Y_Coord_ComboBox.setObjectName("Y_Coord_ComboBox")
        self.Y_Coord_ComboBox.addItem("")
        self.Y_Coord_ComboBox.addItem("")
        self.Add_Remove_Supports_Grid.addWidget(self.Y_Coord_ComboBox, 1, 2, 1, 1)
        self.X_Coord_Support_Label = QtWidgets.QLabel(self.groupBox_10)
        self.X_Coord_Support_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Coord_Support_Label.setObjectName("X_Coord_Support_Label")
        self.Add_Remove_Supports_Grid.addWidget(self.X_Coord_Support_Label, 0, 1, 1, 1)
        self.Remove_Support_Button = QtWidgets.QPushButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Remove_Support_Button.sizePolicy().hasHeightForWidth())
        self.Remove_Support_Button.setSizePolicy(sizePolicy)
        self.Remove_Support_Button.setObjectName("Remove_Support_Button")
        self.Add_Remove_Supports_Grid.addWidget(self.Remove_Support_Button, 2, 2, 1, 1)
        self.Support_Node_LEdit = QtWidgets.QLineEdit(self.groupBox_10)
        self.Support_Node_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Support_Node_LEdit.setObjectName("Support_Node_LEdit")
        self.Add_Remove_Supports_Grid.addWidget(self.Support_Node_LEdit, 1, 0, 1, 1)
        self.Plot_Supports_Button = QtWidgets.QPushButton(self.groupBox_10)
        self.Plot_Supports_Button.setObjectName("Plot_Supports_Button")
        self.Add_Remove_Supports_Grid.addWidget(self.Plot_Supports_Button, 3, 0, 1, 3)
        self.Add_Support_Button = QtWidgets.QPushButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Add_Support_Button.sizePolicy().hasHeightForWidth())
        self.Add_Support_Button.setSizePolicy(sizePolicy)
        self.Add_Support_Button.setObjectName("Add_Support_Button")
        self.Add_Remove_Supports_Grid.addWidget(self.Add_Support_Button, 2, 0, 1, 2)
        self.horizontalLayout_13.addLayout(self.Add_Remove_Supports_Grid)
        self.verticalLayout_8.addWidget(self.groupBox_10)
        self.verticalLayout_8.setStretch(0, 2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.Supports_Tab, "")
        self.Solve_Tab = QtWidgets.QWidget()
        self.Solve_Tab.setObjectName("Solve_Tab")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.Solve_Tab)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_12 = QtWidgets.QGroupBox(self.Solve_Tab)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Post_Processing_Table = QtWidgets.QTableWidget(self.groupBox_12)
        self.Post_Processing_Table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Post_Processing_Table.setAlternatingRowColors(True)
        self.Post_Processing_Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Post_Processing_Table.setObjectName("Post_Processing_Table")
        self.Post_Processing_Table.setColumnCount(0)
        self.Post_Processing_Table.setRowCount(0)
        self.horizontalLayout_16.addWidget(self.Post_Processing_Table)
        self.verticalLayout_10.addWidget(self.groupBox_12)
        self.groupBox_11 = QtWidgets.QGroupBox(self.Solve_Tab)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Solve_Truss_Button = QtWidgets.QPushButton(self.groupBox_11)
        self.Solve_Truss_Button.setEnabled(False)
        self.Solve_Truss_Button.setObjectName("Solve_Truss_Button")
        self.verticalLayout_12.addWidget(self.Solve_Truss_Button)
        self.verticalLayout_10.addWidget(self.groupBox_11)
        self.groupBox_13 = QtWidgets.QGroupBox(self.Solve_Tab)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Displacement_Button = QtWidgets.QPushButton(self.groupBox_13)
        self.Displacement_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Displacement_Button.sizePolicy().hasHeightForWidth())
        self.Displacement_Button.setSizePolicy(sizePolicy)
        self.Displacement_Button.setObjectName("Displacement_Button")
        self.gridLayout_3.addWidget(self.Displacement_Button, 1, 1, 1, 1)
        self.Setup_Button = QtWidgets.QPushButton(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Setup_Button.sizePolicy().hasHeightForWidth())
        self.Setup_Button.setSizePolicy(sizePolicy)
        self.Setup_Button.setObjectName("Setup_Button")
        self.gridLayout_3.addWidget(self.Setup_Button, 0, 0, 1, 1)
        self.Axial_Force_Button = QtWidgets.QPushButton(self.groupBox_13)
        self.Axial_Force_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Axial_Force_Button.sizePolicy().hasHeightForWidth())
        self.Axial_Force_Button.setSizePolicy(sizePolicy)
        self.Axial_Force_Button.setObjectName("Axial_Force_Button")
        self.gridLayout_3.addWidget(self.Axial_Force_Button, 1, 0, 1, 1)
        self.Reactions_Button = QtWidgets.QPushButton(self.groupBox_13)
        self.Reactions_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reactions_Button.sizePolicy().hasHeightForWidth())
        self.Reactions_Button.setSizePolicy(sizePolicy)
        self.Reactions_Button.setObjectName("Reactions_Button")
        self.gridLayout_3.addWidget(self.Reactions_Button, 0, 1, 1, 1)
        self.Save_Figure_Button = QtWidgets.QPushButton(self.groupBox_13)
        self.Save_Figure_Button.setObjectName("Save_Figure_Button")
        self.gridLayout_3.addWidget(self.Save_Figure_Button, 2, 0, 1, 2)
        self.verticalLayout_11.addLayout(self.gridLayout_3)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_14)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_14)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_14)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.Displacement_Factor_LEdit = QtWidgets.QLineEdit(self.groupBox_14)
        self.Displacement_Factor_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Displacement_Factor_LEdit.setObjectName("Displacement_Factor_LEdit")
        self.gridLayout_2.addWidget(self.Displacement_Factor_LEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_14)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.Line_Width_LEdit = QtWidgets.QLineEdit(self.groupBox_14)
        self.Line_Width_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Line_Width_LEdit.setObjectName("Line_Width_LEdit")
        self.gridLayout_2.addWidget(self.Line_Width_LEdit, 1, 1, 1, 1)
        self.Label_Offset_LEdit = QtWidgets.QLineEdit(self.groupBox_14)
        self.Label_Offset_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Offset_LEdit.setObjectName("Label_Offset_LEdit")
        self.gridLayout_2.addWidget(self.Label_Offset_LEdit, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_14)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 2, 1, 1)
        self.Arrow_Length_LEdit = QtWidgets.QLineEdit(self.groupBox_14)
        self.Arrow_Length_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Arrow_Length_LEdit.setObjectName("Arrow_Length_LEdit")
        self.gridLayout_2.addWidget(self.Arrow_Length_LEdit, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_14)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.Arrow_Head_Size_LEdit = QtWidgets.QLineEdit(self.groupBox_14)
        self.Arrow_Head_Size_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Arrow_Head_Size_LEdit.setObjectName("Arrow_Head_Size_LEdit")
        self.gridLayout_2.addWidget(self.Arrow_Head_Size_LEdit, 1, 3, 1, 1)
        self.Arrow_Line_Width_LEdit = QtWidgets.QLineEdit(self.groupBox_14)
        self.Arrow_Line_Width_LEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Arrow_Line_Width_LEdit.setObjectName("Arrow_Line_Width_LEdit")
        self.gridLayout_2.addWidget(self.Arrow_Line_Width_LEdit, 2, 3, 1, 1)
        self.horizontalLayout_17.addLayout(self.gridLayout_2)
        self.verticalLayout_11.addWidget(self.groupBox_14)
        self.verticalLayout_10.addWidget(self.groupBox_13)
        self.verticalLayout_10.setStretch(0, 10)
        self.verticalLayout_10.setStretch(1, 1)
        self.horizontalLayout_14.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.Solve_Tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.Left_Frame)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.Matplotlib_Frame = QtWidgets.QFrame(self.tab)
        self.Matplotlib_Frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Matplotlib_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Matplotlib_Frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Matplotlib_Frame.setObjectName("Matplotlib_Frame")
        self.horizontalLayout_18.addWidget(self.Matplotlib_Frame)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.Tool_Select = QtWidgets.QToolButton(self.tab_2)
        self.Tool_Select.setObjectName("Tool_Select")
        self.horizontalLayout_19.addWidget(self.Tool_Select)
        self.Tool_Pan = QtWidgets.QToolButton(self.tab_2)
        self.Tool_Pan.setObjectName("Tool_Pan")
        self.horizontalLayout_19.addWidget(self.Tool_Pan)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.graphicsView.setSceneRect(QtCore.QRectF(-32000.0, -32000.0, 64000.0, 64000.0))
        self.graphicsView.setAlignment(QtCore.Qt.AlignCenter)
        self.graphicsView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.graphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.graphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsView.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.graphicsView.setRubberBandSelectionMode(QtCore.Qt.IntersectsItemBoundingRect)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_13.addWidget(self.graphicsView)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget_2)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1181, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPySEAD_Truss = QtWidgets.QAction(MainWindow)
        self.actionPySEAD_Truss.setObjectName("actionPySEAD_Truss")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionDarkMode = QtWidgets.QAction(MainWindow)
        self.actionDarkMode.setObjectName("actionDarkMode")
        self.actionLightMode = QtWidgets.QAction(MainWindow)
        self.actionLightMode.setObjectName("actionLightMode")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionPySEAD_Truss)
        self.menuOptions.addAction(self.actionDarkMode)
        self.menuOptions.addAction(self.actionLightMode)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PySEAD Truss 2D"))
        self.groupBox.setTitle(_translate("MainWindow", "Nodes Table"))
        self.Nodes_Table_Widget.setSortingEnabled(False)
        item = self.Nodes_Table_Widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NODE"))
        item = self.Nodes_Table_Widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X"))
        item = self.Nodes_Table_Widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Add / Update / Remove Nodes"))
        self.Node_Number_LEdit.setText(_translate("MainWindow", "1"))
        self.X_Coord_Label.setText(_translate("MainWindow", "X Coordinate"))
        self.Y_Coord_Label.setText(_translate("MainWindow", "Y Coordinate"))
        self.Node_Number_Label.setText(_translate("MainWindow", "Node Number"))
        self.Add_Node_Button.setText(_translate("MainWindow", "Add Node"))
        self.Plot_Nodes_Button.setText(_translate("MainWindow", "Plot Nodes"))
        self.Remove_Node_Button.setText(_translate("MainWindow", "Remove Selected"))
        self.Renumber_Nodes_Button.setText(_translate("MainWindow", "Renumber Nodes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Nodes_Tab), _translate("MainWindow", "Nodes"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Elements Table"))
        self.Element_Table_Widget.setSortingEnabled(False)
        item = self.Element_Table_Widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "BAR"))
        item = self.Element_Table_Widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NODE 1"))
        item = self.Element_Table_Widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NODE 2"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Add / Update / Remove Elements"))
        self.Bar_Number_Label.setText(_translate("MainWindow", "Bar Number"))
        self.Node_1_Label.setText(_translate("MainWindow", "Node 1"))
        self.Add_Bar_Button.setText(_translate("MainWindow", "Add Bar"))
        self.Node_2_Label.setText(_translate("MainWindow", "Node 2"))
        self.Bar_Number_LEdit.setText(_translate("MainWindow", "1"))
        self.Plot_Nodes_and_Bars_Button.setText(_translate("MainWindow", "Plot Nodes and Bars"))
        self.Remove_Bar_Button.setText(_translate("MainWindow", "Remove Selected"))
        self.Renumber_Bar_Button.setText(_translate("MainWindow", "Renumber Bars"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Elements_Tab), _translate("MainWindow", "Elements"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Materials Table"))
        self.Material_Table_Widget.setSortingEnabled(False)
        item = self.Material_Table_Widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "BAR"))
        item = self.Material_Table_Widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CROSS AREA"))
        item = self.Material_Table_Widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ELASTICITY"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Add / Update / Remove Materials"))
        self.Area_Label.setText(_translate("MainWindow", "Cross-sectional Area"))
        self.Area_LEdit.setText(_translate("MainWindow", "0.001"))
        self.Elasticity_LEdit.setText(_translate("MainWindow", "200000000"))
        self.Elasticity_Label.setText(_translate("MainWindow", "Elasticity"))
        self.Update_Material_Button.setText(_translate("MainWindow", "Update Selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Material_Tab), _translate("MainWindow", "Materials"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Forces Table"))
        self.Force_Table_Widget.setSortingEnabled(False)
        item = self.Force_Table_Widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NODE"))
        item = self.Force_Table_Widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FORCE X DIR"))
        item = self.Force_Table_Widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FORCE Y DIR"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Add / Update / Remove Forces"))
        self.Force_Y_Label.setText(_translate("MainWindow", "Force Y-Direction"))
        self.Force_Node_Number_Label.setText(_translate("MainWindow", "Node Number"))
        self.Remove_Force_Button.setText(_translate("MainWindow", "Remove Selected"))
        self.Force_X_Label.setText(_translate("MainWindow", "Force X-Direction"))
        self.Plot_Forces_Button.setText(_translate("MainWindow", "Plot Forces"))
        self.Add_Force_Button.setText(_translate("MainWindow", "Add Force"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Forces_Tab), _translate("MainWindow", "Forces"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Supports Table"))
        self.Support_Table_Widget.setSortingEnabled(False)
        item = self.Support_Table_Widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NODE"))
        item = self.Support_Table_Widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PINNED X"))
        item = self.Support_Table_Widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PINNED Y"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Add / Update / Remove Supports"))
        self.Support_Node_Label.setText(_translate("MainWindow", "Node Number"))
        self.X_Coord_ComboBox.setItemText(0, _translate("MainWindow", "Yes"))
        self.X_Coord_ComboBox.setItemText(1, _translate("MainWindow", "No"))
        self.Y_Coord_Support_Label.setText(_translate("MainWindow", "Y Coordinate"))
        self.Y_Coord_ComboBox.setItemText(0, _translate("MainWindow", "Yes"))
        self.Y_Coord_ComboBox.setItemText(1, _translate("MainWindow", "No"))
        self.X_Coord_Support_Label.setText(_translate("MainWindow", "X Coordinate"))
        self.Remove_Support_Button.setText(_translate("MainWindow", "Remove Selected"))
        self.Plot_Supports_Button.setText(_translate("MainWindow", "Plot Supports"))
        self.Add_Support_Button.setText(_translate("MainWindow", "Add Support"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Supports_Tab), _translate("MainWindow", "Supports"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Post Processing Table"))
        self.Post_Processing_Table.setSortingEnabled(False)
        self.groupBox_11.setTitle(_translate("MainWindow", "Solver"))
        self.Solve_Truss_Button.setText(_translate("MainWindow", "Solve Truss"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Show Truss"))
        self.Displacement_Button.setText(_translate("MainWindow", "Displacement"))
        self.Setup_Button.setText(_translate("MainWindow", "Setup"))
        self.Axial_Force_Button.setText(_translate("MainWindow", "Axial Force"))
        self.Reactions_Button.setText(_translate("MainWindow", "Reactions"))
        self.Save_Figure_Button.setText(_translate("MainWindow", "Save Figure"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Plot Modifiers"))
        self.label.setText(_translate("MainWindow", "Displacement Factor"))
        self.label_4.setText(_translate("MainWindow", "Label Offset"))
        self.label_2.setText(_translate("MainWindow", "Arrow Length"))
        self.Displacement_Factor_LEdit.setText(_translate("MainWindow", "100"))
        self.label_5.setText(_translate("MainWindow", "Arrow Head Size"))
        self.Line_Width_LEdit.setText(_translate("MainWindow", "2"))
        self.Label_Offset_LEdit.setText(_translate("MainWindow", "0.12"))
        self.label_6.setText(_translate("MainWindow", "Arrow Line Width"))
        self.Arrow_Length_LEdit.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "Line Width"))
        self.Arrow_Head_Size_LEdit.setText(_translate("MainWindow", "0.05"))
        self.Arrow_Line_Width_LEdit.setText(_translate("MainWindow", "2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Solve_Tab), _translate("MainWindow", "Solve"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Matplotlib"))
        self.Tool_Select.setText(_translate("MainWindow", "..."))
        self.Tool_Pan.setText(_translate("MainWindow", "..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "QtGraphics (Experimental)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionPySEAD_Truss.setText(_translate("MainWindow", "PySEAD Truss"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionDarkMode.setText(_translate("MainWindow", "Dark"))
        self.actionLightMode.setText(_translate("MainWindow", "Light"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

